### ISSUE TITLE
Got an error when registering with a single name 

### ISSUE THREAD

**Issue by ShahriarShafin** [Ingenuity-2-0/SmartTransportSystem#6]
first_name, last_name = full_name.rsplit(maxsplit=1)    # splitting name as reverse order 

![image](https://user-images.githubusercontent.com/32214710/112530583-ce5f5400-8dd0-11eb-8ba1-f10c1c74ffa1.png)

**Comment by SabbirHosen** [comment]
"Got an error when registering with a single name" is soved

**Comment by SabbirHosen** [comment]
"Got an error when registering with a single name" is solved
